(()=>{"use strict";
const KEY="sjz-community-mobile-data-v1";
const empty={practice_attempts:[],wrong_questions:[],review_schedule:[],wrong_inbox:[],daily_tasks:[],questions:[],question_knowledge:[],knowledge_points:[]};
let db=load();
const view=document.querySelector("#view");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const today=()=>{const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null");return x&&typeof x==="object"?merge(empty,x):structuredClone(empty)}catch{return structuredClone(empty)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function merge(base,incoming){const out=JSON.parse(JSON.stringify(base));for(const k of Object.keys(out)){if(Array.isArray(incoming?.[k]))out[k]=incoming[k].map(x=>({...x}));}return out}
function idOf(k,x){return x?.wrong_id||x?.inbox_id||x?.question_id||x?.source_id||(k==="daily_tasks"?`${x.date}|${x.task_type}`:k==="review_schedule"?`${x.wrong_id}|${x.stage}|${x.scheduled_at}`:null)}
function mergeData(incoming){for(const k of Object.keys(empty)){if(!Array.isArray(incoming?.[k]))continue;const map=new Map(db[k].map(x=>[idOf(k,x)||JSON.stringify(x),x]));for(const x of incoming[k]){const id=idOf(k,x)||JSON.stringify(x);map.set(id,{...(map.get(id)||{}),...x});}db[k]=[...map.values()];}save();}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function syncFile(){return {format:"shijiazhuang-community-sync-v1",version:1,exported_at:new Date().toISOString(),source:"mobile",...db}}
function wrongCount(x){return Math.max(0,Number(x.wrong_count||1))}
function wrongDate(x){return String(x.first_wrong_at||x.wrong_date||x.created_at||x.recorded_at||'').slice(0,10)||'日期未记录'}
function dueGroups(rows){const m=new Map();for(const x of rows.filter(x=>x.status==='active'&&String(x.next_review_at||'')<=today())){const k=wrongDate(x);if(!m.has(k))m.set(k,{date:k,count:0,wrong_ids:[]});m.get(k).count+=wrongCount(x);m.get(k).wrong_ids.push(x.wrong_id)}return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date))}
function renderHome(){const active=db.wrong_questions.filter(x=>x.status==='active'),due=active.filter(x=>String(x.next_review_at||'')<=today()),groups=dueGroups(active),attempts=db.practice_attempts.filter(x=>(x.recorded_at||'').slice(0,10)===today()),by={};attempts.forEach(x=>{const m=x.module||'未分类';by[m]=(by[m]||0)+Math.max(0,Number(x.actual_count||0)-Number(x.correct_count||0))});const modules=Object.entries(by).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);
view.innerHTML='<div class="card"><div class="muted">今天</div><div class="big">'+due.reduce((n,x)=>n+wrongCount(x),0)+'</div><p>道到期/逾期错题</p><div class="actions"><button class="primary" data-go="wrong">先复习</button></div></div><div class="card"><h3>今天各模块错题</h3>'+(modules.length?modules.map(([m,n])=>'<div class="row"><strong>'+esc(m)+'</strong>：'+n+' 道</div>').join(''):'<div class="row">今天还没有记录错题</div>')+'<p>今日错题合计：<strong>'+modules.reduce((n,[,v])=>n+v,0)+'道</strong></p><h3>今天该复习哪一天？</h3>'+(groups.length?groups.map(g=>'<div class="row"><strong>'+esc(g.date.slice(5))+'</strong> 记下的错题：'+g.count+' 道</div>').join(''):'<div class="row">今天没有到期/逾期错题</div>')+'</div><div class="card"><p class="muted">手机数据只保存在本机浏览器。同步时通过 JSON 文件传回电脑。</p></div>';
view.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>render(b.dataset.go))}
function renderQuick(){view.innerHTML=`<div class="card"><h2>快速记错</h2><p class="muted">手机做题最省事的方式：复制题干和选项 → 粘贴 → 选错因 → 保存。先别整理。</p><form id="q"><label>题目文本<textarea name="text" required placeholder="把题干和选项粘贴到这里"></textarea></label><label>错题原因<select name="wrong_reason"><option>知识点不会</option><option>方法不会</option><option>粗心</option><option>时间不够</option><option>蒙对</option><option value="">稍后再判断</option></select></label><button class="primary" type="submit">先存起来</button></form><p id="msg"></p></div><div class="card"><h3>待整理 ${db.wrong_inbox.filter(x=>x.status==="pending").length} 道</h3>${db.wrong_inbox.filter(x=>x.status==="pending").slice().reverse().map(x=>`<div class="row">${esc(x.text)}<div class="muted">${esc(x.wrong_reason||"未记录")} · ${esc((x.created_at||"").slice(0,10))}</div></div>`).join("")||"<p class='muted'>暂无。</p>"}</div>`;document.querySelector("#q").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.wrong_inbox.push({inbox_id:"mi_"+Date.now(),text:String(f.get("text")),exam_line:"社区",wrong_reason:String(f.get("wrong_reason")||""),status:"pending",created_at:new Date().toISOString()});save();renderQuick();}}
function renderWrong(){const rows=db.wrong_questions.filter(x=>x.status==='active'),groups=dueGroups(rows),total=rows.reduce((n,x)=>n+wrongCount(x),0),due=groups.reduce((n,g)=>n+g.count,0);view.innerHTML='<div class="card"><h2>错题复习</h2><p><strong>今天只看日期和数量。</strong></p>'+(groups.length?groups.map(g=>'<div class="row"><strong>'+esc(g.date.slice(5))+' 记下的错题：'+g.count+' 道</strong><div class="actions"><button data-date="'+esc(g.date)+'" data-result="已掌握">这批掌握</button><button data-date="'+esc(g.date)+'" data-result="重错">这批重错</button></div></div>').join(''):'<p class="muted">今天没有到期/逾期错题</p>')+'<p class="muted">复习节奏：+1 → +3 → +7 → +14 → +30；重错后重新从+1天开始。</p><p>当前有效错题：<strong>'+total+'</strong> 道 · 今天应复习：<strong>'+due+'</strong> 道</p></div>';view.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{const g=groups.find(x=>x.date===b.dataset.date);if(!g)return;g.wrong_ids.forEach(id=>review(id,b.dataset.result));});}
function review(id,result){const x=db.wrong_questions.find(v=>v.wrong_id===id);if(!x)return;const stage=Number(x.review_stage||0),offsets=[1,3,7,14,30];if(result==="重错"){x.mastery="未掌握";x.repeated_wrong=true;x.wrong_count=Number(x.wrong_count||1)+1;x.review_stage=0;x.next_review_at=addDays(today(),1);x.status="active";}else if(stage>=4){x.mastery="已掌握";x.status="completed";x.next_review_at=null;}else{x.review_stage=stage+1;x.next_review_at=addDays(today(),offsets[stage]);x.mastery="复习中";}db.review_schedule.push({wrong_id:id,stage,result,scheduled_at:today()});save();renderWrong();}
function addDays(s,n){const d=new Date(s+"T00:00:00");d.setDate(d.getDate()+n);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function mobileActionPlan(){const priorities={"社区专业知识":100,"法律":98,"社会工作实务":96,"社会工作综合能力":94,"政治":92,"时政":90,"职测-逻辑判断":88,"职测-片段阅读":86,"职测-资料分析":84,"公文":80,"经济":76,"职测-逻辑填空":74,"职测-定义判断":72,"职测-语句表达":70,"管理":66,"职测-类比推理":62,"职测-图形推理":60,"人文历史":58,"科技":54,"地理国情":50,"职测-数量关系":50};const quotas={"社区专业知识":120,"法律":120,"社会工作实务":100,"社会工作综合能力":90,"政治":90,"时政":100,"公文":70,"经济":60,"管理":50,"人文历史":50,"科技":40,"地理国情":40,"职测-片段阅读":80,"职测-语句表达":50,"职测-逻辑填空":60,"职测-逻辑判断":80,"职测-定义判断":60,"职测-类比推理":50,"职测-图形推理":50,"职测-数量关系":50,"职测-资料分析":80};const due=db.wrong_questions.filter(x=>x.status==="active"&&String(x.next_review_at||"")<=today());if(due.length)return {type:"review"};const rows=Object.keys(quotas).map(m=>{const a=db.practice_attempts.filter(x=>x.module===m),actual=a.reduce((n,x)=>n+Number(x.actual_count||0),0),correct=a.reduce((n,x)=>n+Number(x.correct_count||0),0),acc=actual?correct/actual:null,target=actual===0?quotas[m]:(acc<.6?80:acc<.7?60:acc<.85?50:40),done=db.practice_attempts.filter(x=>x.module===m&&(x.recorded_at||"").slice(0,10)===today()).reduce((n,x)=>n+Number(x.actual_count||0),0),score=(priorities[m]||40)*(1+(acc==null ? 0.35:1-acc))+(acc==null?25:0);return {module:m,accuracy:acc,target,remaining:Math.max(0,target-done),score};}).filter(x=>x.remaining>0).sort((a,b)=>b.score-a.score);return rows[0]||null;}
function renderPractice(){const a=mobileActionPlan();if(!a){view.innerHTML='<div class="card"><h2>今日刷题</h2><p>今天当前专项任务已完成。</p></div>';return}if(a.type==="review"){view.innerHTML='<div class="card"><h2>今日先复习错题</h2><p>系统已经发现到期/逾期错题。</p><button class="primary" data-go="wrong">去错题复习</button></div>';view.querySelector("[data-go]").onclick=()=>render("wrong");return}const knowledgeRows=db.practice_attempts.filter(x=>x.module===a.module&&x.knowledge_name);const kb={};knowledgeRows.forEach(x=>{const k=x.knowledge_name;kb[k]??={actual:0,correct:0};kb[k].actual+=Number(x.actual_count||0);kb[k].correct+=Number(x.correct_count||0)});const kbs=Object.entries(kb).map(([name,x])=>({name,acc:x.actual?x.correct/x.actual:null})).sort((x,y)=>(x.acc??-1)-(y.acc??-1))[0];view.innerHTML='<div class="card"><h2>今日刷题</h2><div class="notice"><strong>'+esc(a.module)+'</strong><br>按重要度＋正确率自动分配；本轮最低40题。<br>建议：<strong>'+a.target+'</strong>题 · 还差 <strong>'+a.remaining+'</strong>题</div><form id="p"><input type="hidden" name="module" value="'+esc(a.module)+'"><input type="hidden" name="knowledge_name" value="'+esc(kbs?.name||"")+'"><label>实际题数<input name="actual_count" type="number" min="0" value="'+a.remaining+'" required></label><label>正确题数<input name="correct_count" type="number" min="0" value="'+a.remaining+'" required></label><label>学习分钟<input name="study_minutes" type="number" min="0"></label><button class="primary" type="submit">保存</button></form><p class="muted">只记录实际题数＋正确题数＋时间；错题、正确率、复习日期自动计算。</p><p id="msg"></p></div>';document.querySelector("#p").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),a={source_id:"mobile:"+Date.now(),exam_line:"社区",module:String(f.get("module")),knowledge_name:String(f.get("knowledge_name")||""),training_type:"专项",planned_count:Number(f.get("actual_count")||0),actual_count:Number(f.get("actual_count")||0),correct_count:Number(f.get("correct_count")||0),study_minutes:Number(f.get("study_minutes")||0),recorded_at:new Date().toISOString()};const msg=document.querySelector("#msg");if(a.correct_count>a.actual_count){msg.textContent="正确题数不能超过实际题数";return}db.practice_attempts.push(a);const wrong=Math.max(0,a.actual_count-a.correct_count);if(wrong){const id="mobile_wq_"+Date.now();db.wrong_questions.push({wrong_id:id,question_id:null,exam_line:"社区",module:a.module,knowledge_id:null,knowledge_name:a.knowledge_name,wrong_reason:null,first_wrong_at:a.recorded_at,last_wrong_at:a.recorded_at,wrong_count:wrong,repeated_wrong_count:0,mastery:"未掌握",review_stage:0,next_review_at:addDays(today(),1),repeated_wrong:false,status:"active"});db.review_schedule.push({wrong_id:id,stage:0,scheduled_at:addDays(today(),1),result:null});}save();msg.textContent="已保存："+wrong+"道错题；下一步由系统自动安排。";e.target.reset();}}}
function renderSync(){view.innerHTML=`<div class="card"><h2>手机 ↔ 电脑</h2><p class="muted">这里不联网传数据，只通过一个备份文件搬运数据。</p><div class="notice"><strong>电脑 → 手机</strong><br>电脑端点击“导出手机同步文件” → 把 .json 文件发到手机 → 点下面“导入电脑文件”。</div><div class="actions"><button id="imp" class="primary">导入电脑同步文件</button><input id="file" class="hidden" type="file" accept=".json,application/json"></div><hr><div class="notice"><strong>手机 → 电脑</strong><br>手机做完题/记完错题后 → 点“导出手机同步文件” → 把文件传回电脑 → 电脑端点击“导入手机数据”。</div><button id="exp" class="primary">导出手机同步文件</button><p id="syncmsg"></p></div><div class="card"><p>本机记录：待整理 ${db.wrong_inbox.length} · 刷题 ${db.practice_attempts.length} · 错题 ${db.wrong_questions.length}</p><button id="clear">清空本机数据</button></div>`;document.querySelector("#exp").onclick=()=>download("石家庄社区备考_手机同步_"+today()+".json",syncFile());document.querySelector("#imp").onclick=()=>document.querySelector("#file").click();document.querySelector("#file").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error("同步文件超过5MB");const x=JSON.parse(await file.text());if(x.format!=="shijiazhuang-community-sync-v1")throw Error("不是本系统同步文件");mergeData(x);document.querySelector("#syncmsg").textContent="导入成功：已合并到本机，重复导入不会重复添加。";renderSync();}catch(err){document.querySelector("#syncmsg").textContent="导入失败："+err.message;}};document.querySelector("#clear").onclick=()=>{if(confirm("确定清空这台手机上的本机数据吗？请先导出备份。")){db=structuredClone(empty);save();renderSync();}}}
function render(name){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="home")renderHome();if(name==="quick")renderQuick();if(name==="wrong")renderWrong();if(name==="practice")renderPractice();if(name==="sync")renderSync()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>render(b.dataset.view));if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});render("home");
})();